name: Build/release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
